### ISSUE TITLE
UI display issues after recent updates

### ISSUE THREAD

**Issue by paulo-rossy** [open-condo-software/condo#6418]
Hello, team!

After a recent update I’ve run into UI display problems on several pages—most notably the sign-in page.

I suspect the issue might be cache-related. I deleted the `.next`, `.turbo`, and `dist` folders in `apps/condo`, but that didn’t help.

I also tried rebuilding the packages with
`yarn workspace @app/condo build:deps`, yet the problem persisted.

Removing `packages/ui/dist` didn’t solve it either.

Could you advise what might be causing this? I’ve attached screenshots for reference.

<img width="446" height="683" alt="Image" src="https://github.com/user-attachments/assets/5a105f01-6985-460a-a46f-b5b5deb20543" />

<img width="241" height="496" alt="Image" src="https://github.com/user-attachments/assets/8d0e3dc5-b454-4648-98f6-c1884dbf8b8d" />

**Comment by toplenboren** [comment]
Hello! @paulo-rossy. Thanks for the issue! 🚀 

We faced the same issue after the NextJS update #6313. We figured it was related to us using emotionJS incorrectly, which resulted in page being rendered faster then the styles loaded

Since then we have implemented a few fixes, for example: #6384

In these fixes we have replaced emotionJS with css modules. Please update the project to check out if these fixes work for you

**Comment by paulo-rossy** [comment]
@toplenboren Hello! The problem with the UI rendering is still not resolved. However, when I run the project in Docker, the UI looks correct.

I suspect the issue might be related to @open-condo/ui, but I’m not completely sure. I tried setting up the project from scratch, and I still have the same UI rendering problems. The issue also appears in dev mode.

I also tried building @open-condo/ui separately, but that didn’t help either.

My environment:
– Node.js: 22.21.1
– OS: Windows 11
– Terminal: Git Bash

**Comment by ayaanshkk** [comment]
@paulo-rossy did you manage to get the UI issue resolved?
